refactor for cleaner fail-handling

diff --git a/templates/usr/local/sbin/cicd/run_all_tests.sh.j2 b/templates/usr/local/sbin/cicd/run_all_tests.sh.j2
--- a/templates/usr/local/sbin/cicd/run_all_tests.sh.j2
+++ b/templates/usr/local/sbin/cicd/run_all_tests.sh.j2
@@ -16,9 +16,12 @@ fi
 
 for FILE in /etc/systemd/system/ansible-test-$1-*.service
 do
-  svc=$(echo $FILE | cut -d '/' -f5)
-  echo "Starting '$svc'"
-  systemctl start "$svc"
+  if ! echo "$FILE" | grep -q 'fail'
+  then
+    svc=$(echo "$FILE" | cut -d '/' -f5)
+    echo "Starting '$svc'"
+    systemctl start "$svc"
+  fi
 done
 
 echo ''
diff --git a/templates/usr/local/sbin/cicd/run_molecule_job.sh.j2 b/templates/usr/local/sbin/cicd/run_molecule_job.sh.j2
--- a/templates/usr/local/sbin/cicd/run_molecule_job.sh.j2
+++ b/templates/usr/local/sbin/cicd/run_molecule_job.sh.j2
@@ -16,10 +16,13 @@ fi
 
 for FILE in /etc/systemd/system/ansible-test-molecule-*$1*.service
 do
-  svc=$(echo $FILE | cut -d '/' -f5)
-  echo "Starting '$svc'"
-  systemctl start "$svc" --no-block
-  journalctl -u "$svc" --no-pager -f
+  if ! echo "$FILE" | grep -q 'fail'
+  then
+    svc=$(echo "$FILE" | cut -d '/' -f5)
+    echo "Starting '$svc'"
+    systemctl start "$svc" --no-block
+    journalctl -u "$svc" --no-pager -f
+  fi
 done
 
 echo ''
